#!/usr/bin/env python3
"""
Generates the synthetic fixture folder used by test_tabular_parser.py.

These stand in for the real-world files task-parser-hardening.txt names
(1-B.xls, Teacher_Information.xlsx) — the actual files live on Sid's machine,
not in this repo. test_tabular_parser.py iterates over whatever's in
fixtures/ dynamically, so dropping the real files in alongside these (or
replacing these) picks them up automatically, no test code changes needed.

Run once with: .venv_test/Scripts/python.exe tests/make_fixtures.py
"""
import io
import os

from openpyxl import Workbook

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")


def _save(name, raw_bytes):
    path = os.path.join(FIXTURES_DIR, name)
    with open(path, "wb") as f:
        f.write(raw_bytes)
    print(f"wrote {name} ({len(raw_bytes)} bytes)")


def _xlsx_bytes(build_fn):
    wb = Workbook()
    build_fn(wb)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# 1. "1-B.xls" stand-in: real xlsx content, .xls extension, junk rows above
#    the header (row 6), matches the exact real-world case named in the task.
def _build_junk_above_header(wb):
    ws = wb.active
    ws.title = "I B"
    ws.append(["ABC Public School"])
    ws.append(["Annual Report - Class I Section B"])
    ws.append([])
    ws.append(["Printed on: 01-04-2024"])
    ws.append([])
    ws.append(["S.No", "Name", "Class", "Sec", "Roll No", "Gender", "DOB", "Father Name", "Mother Name", "Contact"])
    ws.append([1, "amit  kumar", "1", "B", "1", "M", "12/05/2015", "Suresh Kumar", "Anita Kumar", "9876543210"])
    ws.append([2, "priya sharma", "1", "B", "2", "F", "23-08-2015", "Ramesh Sharma", "Sunita Sharma", "9123456789 / 9988776655"])
    ws.append([3, "", "1", "B", "3", "M", "2015-01-15", "Vijay Singh", "Rekha Singh", "not a phone"])
    ws.append(["Total: 3"])


# ---------------------------------------------------------------------------
# 2. Two-row merged header (fill-forward + join)
def _build_two_row_header(wb):
    ws = wb.active
    ws.title = "Sheet1"
    ws.append(["Personal Details", None, None, "Class Details", None, "Contact Details"])
    ws.append(["Name", "Gender", "DOB", "Class", "Sec", "Mobile"])
    ws.append(["Rahul Verma", "Boy", "05/06/2014", "2", "A", "9812345678"])
    ws.append(["Sneha Patil", "Girl", "17/11/2014", "2", "A", "9898989898"])


# ---------------------------------------------------------------------------
# 3. Header-only sheet — no data rows at all.
def _build_header_only(wb):
    ws = wb.active
    ws.title = "Sheet1"
    ws.append(["Sr No", "Student Name", "Class", "Section", "Gender", "DOB", "Contact"])


# ---------------------------------------------------------------------------
# 4. Excel-serial DOBs — plain numbers (no date number_format), the way a
#    badly-exported sheet or a copy-paste-values often leaves them.
def _excel_serial(y, m, d):
    from datetime import date
    return (date(y, m, d) - date(1899, 12, 30)).days


def _build_excel_serial_dob(wb):
    ws = wb.active
    ws.title = "Sheet1"
    ws.append(["Sr No", "Student Name", "Class", "Section", "Gender", "DOB", "Contact"])
    ws.append([1, "Kabir Khan", "5", "A", "Male", _excel_serial(2000, 1, 1), "9000000001"])
    ws.append([2, "Fatima Ali", "5", "A", "Female", _excel_serial(2005, 12, 25), "9000000002"])


# ---------------------------------------------------------------------------
# 5. Multi-sheet, one hidden, one genuinely empty, one with an unrecognized
#    header (no name column at all).
def _build_multi_sheet(wb):
    ws = wb.active
    ws.title = "3A"
    ws.append(["Name", "Grade", "Section", "Gender", "DOB", "Contact"])
    ws.append(["Ishaan Rao", "3", "A", "Boy", "10/10/2016", "9111111111"])

    ws2 = wb.create_sheet("3B")
    ws2.append(["Name", "Grade", "Section", "Gender", "DOB", "Contact"])
    ws2.append(["Meera Joshi", "3", "B", "Girl", "22/02/2016", "9222222222"])
    ws2.sheet_state = "hidden"

    ws3 = wb.create_sheet("Empty Sheet")
    # left genuinely empty

    ws4 = wb.create_sheet("Notes")
    ws4.append(["This document was generated by XYZ software"])
    ws4.append(["Contact IT for support"])


# ---------------------------------------------------------------------------
# "Teacher_Information.xlsx" stand-in: multi-sheet, inconsistent subject
# names, typo emails — the real file lives on Sid's machine, not this repo.
# Teacher import isn't wired to the deterministic tabular_parser (matrix
# layout, not a row-per-record register — see tabular_parser.py's module
# docstring), so this exists purely to prove the "never raises" contract
# holds even when a completely mismatched file shape hits the student-schema
# parser in the test sweep.
def _build_teacher_information(wb):
    ws = wb.active
    ws.title = "Primary"
    ws.append(["Teacher Name", "Email", "Eng", "Maths", "EVS"])
    ws.append(["Mrs. Kavita Rao", "kavita.rao@gamil.com", "3-A", "", "3-A"])
    ws.append(["Mr. Sameer Joshi", "sameer.joshi@school.edu", "", "3-A,3-B", ""])

    ws2 = wb.create_sheet("Secondary")
    ws2.append(["Teacher", "Email Id", "English", "Mathematics", "Science"])
    ws2.append(["Ms. Anjali Nair", "anjali.nair@yahooo.com", "9-A", "", ""])


FILES = {
    "1-B.xls": lambda: _xlsx_bytes(_build_junk_above_header),
    "student_two_row_merged_header.xlsx": lambda: _xlsx_bytes(_build_two_row_header),
    "student_header_only_sheet.xlsx": lambda: _xlsx_bytes(_build_header_only),
    "student_excel_serial_dob.xlsx": lambda: _xlsx_bytes(_build_excel_serial_dob),
    "student_multi_sheet_hidden_empty.xlsx": lambda: _xlsx_bytes(_build_multi_sheet),
    "Teacher_Information.xlsx": lambda: _xlsx_bytes(_build_teacher_information),
}


def _html_as_xls():
    html = """<html><head><title>Export</title></head><body>
    <table border="1">
    <tr><th>Sr No</th><th>Name</th><th>Class</th><th>Sec</th><th>Gender</th><th>DOB</th><th>Contact</th></tr>
    <tr><td>1</td><td>Devansh  Gupta</td><td>4</td><td>C</td><td>M</td><td>14/03/2015</td><td>9333333333</td></tr>
    <tr><td>2</td><td>Aisha Reddy</td><td>4</td><td>C</td><td>F</td><td>29/09/2015</td><td>+91 94444 44444</td></tr>
    </table></body></html>"""
    return html.encode("utf-8")


def _cp1252_csv():
    # café/résumé-style accented characters that break under strict utf-8.
    text = (
        "Sr No,Name,Class,Section,Gender,DOB,Father Name,Contact\r\n"
        "1,Zoe Dsouza,6,A,F,19/07/2013,Andr\xe9 Dsouza,9555555555\r\n"
        "2,Rene\xe9 Fernandes,6,A,F,04/05/2013,Jos\xe9 Fernandes,9666666666\r\n"
    )
    return text.encode("cp1252")


def _plain_csv():
    text = (
        "Sr No,Name,Class,Section,Gender,DOB,Contact,Email\n"
        "1,Arjun Mehta,7,B,Male,2012-08-30,9777777777,arjun@gamil.com\n"
        "2,Kavya Nair,7,B,Female,31/12/2012,9888888888,kavya@yahoo.com\n"
        "3,,7,B,Male,01/01/2012,9700000000,noone@nowhere.com\n"  # missing name -> excluded
    )
    return text.encode("utf-8")


def _tsv_file():
    text = (
        "Sr No\tName\tClass\tSection\tGender\tDOB\tContact\n"
        "1\tOm Prakash\t8\tA\tMale\t02/02/2011\t9012345678\n"
    )
    return text.encode("utf-8")


def _summary_rows_csv():
    text = (
        "Sr No,Name,Class,Section,Gender,DOB,Contact\n"
        "1,Diya Bose,9,A,Female,15/06/2010,9111122223\n"
        "2,Karan Malhotra,9,A,Male,20/07/2010,9111122224\n"
        "SR NO,NAME,CLASS,SECTION,GENDER,DOB,CONTACT\n"  # repeated header pasted mid-sheet
        "Total: 2,,,,,,\n"
    )
    return text.encode("utf-8")


def _password_protected_xlsx():
    # Real msoffcrypto-encrypted files need a password + the msoffcrypto-tool
    # dependency to construct properly; we don't want that as a project
    # dependency just for a fixture. This is a synthetic OLE compound-file
    # header (D0CF11E0 magic) with an "EncryptedPackage" stream name
    # (UTF-16LE) embedded — enough for sniff_file_type()/_load_ole()'s
    # heuristic to correctly classify it as password-protected, which is the
    # behavior under test (never crash, report the right reason) — not a
    # real openable file.
    magic = b"\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1"
    padding = b"\x00" * 512
    marker = "EncryptedPackage".encode("utf-16-le")
    return magic + padding + marker + padding


def _corrupt_zip():
    # Valid PK local-file-header magic, garbage after it — openpyxl must
    # fail to open this and we must report "file unreadable", not crash.
    return b"PK\x03\x04" + os.urandom(200)


def _empty_file():
    return b""


BYTE_FILES = {
    "student_html_export_as_xls.xls": _html_as_xls,
    "student_html_table_export.html": _html_as_xls,
    "student_cp1252_encoding.csv": _cp1252_csv,
    "student_plain.csv": _plain_csv,
    "student_tab_delimited.tsv": _tsv_file,
    "student_summary_total_rows.csv": _summary_rows_csv,
    "student_password_protected.xlsx": _password_protected_xlsx,
    "student_corrupt_zip.xlsx": _corrupt_zip,
    "empty_file.xlsx": _empty_file,
}


def main():
    os.makedirs(FIXTURES_DIR, exist_ok=True)
    for name, build in FILES.items():
        _save(name, build())
    for name, build in BYTE_FILES.items():
        _save(name, build())


if __name__ == "__main__":
    main()
