// Generated by tools/build_pamphlet_templates.py + tools/add_pamphlet_school_band.py
// — do not edit by hand. PDF points, origin bottom-left (pdf-lib); one entry per template page.
export default {
  "foundational": {
    "width": 595.5,
    "height": 842.25,
    "pages": [
      {
        "qr": {
          "x": 88.64,
          "y": 430.58,
          "size": 119.06
        },
        "url": {
          "baseline": 460.13,
          "size": 20.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.16
        },
        "userId": {
          "baseline": 383.91,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5,
          "maxWidth": 154.56
        },
        "password": {
          "baseline": 350.96,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93,
          "maxWidth": 144.15
        },
        "school": {
          "x0": 30,
          "x1": 565,
          "top": 837.25,
          "bottom": 785.45
        },
        "header": {
          "baseline": 741.44,
          "size": 19.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 297.75
        }
      },
      {
        "qr": {
          "x": 87.51,
          "y": 477.75,
          "size": 121.32
        },
        "url": {
          "baseline": 507.86,
          "size": 20.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.16
        },
        "userId": {
          "baseline": 430.19,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5,
          "maxWidth": 154.56
        },
        "password": {
          "baseline": 396.61,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93,
          "maxWidth": 144.15
        }
      }
    ]
  },
  "middle": {
    "width": 595.5,
    "height": 842.25,
    "pages": [
      {
        "qr": {
          "x": 102.97,
          "y": 419.54,
          "size": 116.76
        },
        "url": {
          "baseline": 448.08,
          "size": 18.25,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 385.58
        },
        "userId": {
          "baseline": 373.54,
          "size": 20.21,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 151.32,
          "maxWidth": 149.4
        },
        "password": {
          "baseline": 342.01,
          "size": 20.21,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 164.9,
          "maxWidth": 136.81
        },
        "school": {
          "x0": 30,
          "x1": 565,
          "top": 837.25,
          "bottom": 785.48
        },
        "header": {
          "baseline": 741.44,
          "size": 19.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 297.75
        }
      },
      {}
    ]
  }
}
