// Generated by tools/build_pamphlet_templates.py — do not edit by hand.
// PDF points, origin bottom-left (pdf-lib); one entry per template page.
export default {
  "foundational": {
    "width": 595.5,
    "height": 842.25,
    "pages": [
      {
        "header": {
          "baseline": 804.69,
          "size": 19.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 291.91
        },
        "qr": {
          "x": 87.51,
          "y": 477.75,
          "size": 121.32
        },
        "url": {
          "baseline": 507.86,
          "size": 20.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.16
        },
        "userId": {
          "baseline": 430.19,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5
        },
        "password": {
          "baseline": 396.61,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93
        },
        "footer": {
          "baseline": 13.54,
          "size": 12.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 296.08
        }
      },
      {
        "qr": {
          "x": 87.51,
          "y": 477.75,
          "size": 121.32
        },
        "url": {
          "baseline": 507.86,
          "size": 20.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.16
        },
        "userId": {
          "baseline": 430.19,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5
        },
        "password": {
          "baseline": 396.61,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93
        },
        "footer": {
          "baseline": 13.54,
          "size": 12.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 296.07
        }
      }
    ]
  },
  "middle": {
    "width": 595.5,
    "height": 842.25,
    "pages": [
      {
        "qr": {
          "x": 87.51,
          "y": 489.05,
          "size": 121.32
        },
        "url": {
          "baseline": 518.72,
          "size": 18.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.15
        },
        "footer": {
          "baseline": 13.54,
          "size": 12.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 296.08
        },
        "header": {
          "baseline": 804.69,
          "size": 19.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 291.91
        },
        "userId": {
          "baseline": 441.49,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5
        },
        "password": {
          "baseline": 407.91,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93
        }
      },
      {
        "footer": {
          "baseline": 13.54,
          "size": 12.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 296.08
        }
      }
    ]
  },
  "foundationalMarathi": {
    "width": 595.5,
    "height": 842.25,
    "pages": [
      {
        "qr": {
          "x": 87.51,
          "y": 477.75,
          "size": 121.32
        },
        "url": {
          "baseline": 507.86,
          "size": 20.97,
          "color": [
            0.12941176470588237,
            0.5882352941176471,
            0.9529411764705882
          ],
          "cx": 381.16
        },
        "userId": {
          "baseline": 430.19,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 138.5
        },
        "password": {
          "baseline": 396.61,
          "size": 21.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "x": 149.93
        },
        "footer": {
          "baseline": 13.54,
          "size": 12.0,
          "color": [
            0.0,
            0.0,
            0.0
          ],
          "cx": 296.07
        }
      }
    ]
  }
}
